FROM node:18-alpine AS build

WORKDIR /frontend

COPY package.json package-lock.json ./

RUN npm install --production=false

COPY . .

RUN npm run build

FROM nginx:1.23-alpine

RUN apk add --no-cache curl

WORKDIR /frontend

COPY --from=build /frontend/* ./
